name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, deploy-actions]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # npm install
      - name: Install Dependencies
        run: npm install

      # lint
      - name: Code Lint
        run: npm run lint
        
      # build
      - name: Vue Build
        run: npm run build
      
      # backup
      - name: Backup
        run: mv /usr/share/nginx/html/dist /usr/share/nginx/html/dist_$(date '+%Y%m%d')

      # deploy
      - name: deploy
        run: mv ./dist /usr/share/nginx/html/dist

      # remove dependencies
      - name: Remove Dependencies
        run: rm -rf *