# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # npm install
      - name: Install Dependencies
        run: npm install

      # lint
      - name: Code Lint
        run: npm run lint
        
      # build
      - name: Vue Build
        run: npm run build
        
      # ssh
      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          local_path: './dist/*'
          remote_path: '/var/www/app'
          args: '-o ConnectTimeout=1200'
      
      # test1
      - name: test1
        run: ls -al
